name: Build EXE Directory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Setze die gewünschte Python-Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE Directory
      run: |
        pyinstaller --onedir your_script.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: your_executable_directory
        path: dist/your_script/*
