name: Build EXE Directory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE Directory
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon ".\icons\icon.ico" --name "Hello_World_App"  "main.py"
        cp -R icons dist/Hello_World_App/

    - name: Install Inno Setup
      run: choco install innosetup --yes

    - name: Build Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Python_Installer
        path: Hello_World_App-Setup.exe
        
    #- name: Upload artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: hello_world_app
    #    path: dist/Hello_World_App/*
