name: Build EXE Directory
on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build EXE Directory
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon ".\icons\icon.ico" --name "Hello_World_App"  "main.py"
        Copy-Item -Path "icons" -Destination "dist/Hello_World_App/" -Recurse
    
    - name: Install Inno Setup
      run: choco install innosetup --yes
    
    - name: Build Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Hello_World_App-Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
